[package]
name = "addi-engine"
version = "0.1.0"
edition = "2024"

[dependencies]
addi-dsp = { workspace = true }
auto_impl = { workspace = true }
enum_dispatch = { workspace = true }
itertools = { workspace = true }
rand = "0.10.2"
rand_pcg = "0.10.2"
realfft = { workspace = true }
rustc-hash = { workspace = true }
serde = { workspace = true }
smallvec = { workspace = true }
topo_sort = "0.4"
tracing = "0.1.41"
wide = { workspace = true }

[dev-dependencies]
criterion = { workspace = true }
serde_json = { workspace = true }

[[bench]]
name = "synth_engine"
harness = false
