[workspace]
resolver = "3"
members = [
    "crates/additizer",
    "crates/addi-dsp",
    "crates/addi-engine",
    "crates/addi-ui-backend",
    "crates/addi-egui",
]
default-members = ["crates/additizer"]

[workspace.dependencies]
addi-dsp = { path = "crates/addi-dsp" }
addi-engine = { path = "crates/addi-engine" }
addi-ui-backend = { path = "crates/addi-ui-backend" }
auto_impl = "1.3"
egui = { version = "0.36.1", default-features = false, features = [
    "bytemuck",
    "default_fonts",
] }
criterion = { version = "0.8.2", features = ["html_reports"] }
enum_dispatch = "0.3"
itertools = "0.15.0"
parking_lot = "0.12.5"
realfft = { version = "3.5" }
rustc-hash = "2.1.3"
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
smallvec = "1.16.1"
wide = "1.7.1"

[profile.release]
codegen-units = 1
lto = "thin"
strip = "symbols"

[profile.profiling]
inherits = "release"
debug = true
strip = "none"
