[package]
name = "addi-ui-backend"
version = "0.1.0"
edition = "2024"

[dependencies]
addi-dsp = { workspace = true }
addi-engine = { workspace = true }
arc-swap = "1.9.2"
atomic_float = "1.1.0"
auto_impl = { workspace = true }
directories = "6.0.0"
enum_dispatch = { workspace = true }
parking_lot = { workspace = true, features = ["serde"] }
rtrb = "0.4.0"
rustc-hash = { workspace = true }
serde = { workspace = true, features = ["rc"] }
serde_json = { workspace = true }
tracing = "0.1.41"
triple_buffer = "9.0.0"
