[package]
name = "addi-dsp"
version = "0.1.0"
edition = "2024"

[dependencies]
enum_dispatch = { workspace = true }
itertools = { workspace = true }
num-complex = "0.4.6"
serde = { workspace = true }
wide = { workspace = true }

[dev-dependencies]
criterion = { workspace = true }
serde_json = { workspace = true }

[[bench]]
name = "svf"
harness = false

[[bench]]
name = "spectral_filter"
harness = false
