[package]
name = "addi-egui"
version = "0.1.0"
edition = "2024"

[dependencies]
addi-dsp = { workspace = true }
addi-engine = { workspace = true }
addi-ui-backend = { workspace = true }
egui = { workspace = true }
egui_extras = { version = "0.36.1", default-features = false }
realfft = { workspace = true }
rustc-hash = { workspace = true }
smallvec = { workspace = true }

[dev-dependencies]
parking_lot = { workspace = true }
